sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lyallsathish/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lyallsathish/react-test npm test -- --coverage

after_success:
  - docker build -t lyallsathish/multi-client ./client
  - docker build -t lyallsathish/multi-nginx ./nginx
  - docker build -t lyallsathish/multi-server ./server
  - docker build -t lyallsathish/multi-worker ./worker
  #LogIn to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those build images and push to docker hub
  - docker push lyallsathish/multi-client
  - docker push lyallsathish/multi-nginx
  - docker push lyallsathish/multi-server
  - docker push lyallsathish/multi-worker
deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: Multi-docker-env-1
  bucket_name: elasticbeanstalk-ap-northeast-1-570539026188
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


